# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Celui Qui Baille
email: jeffyer38130@gmail.com
description: >
  Site personnel de Jerome Celle alias Celui Qui Baille.

baseurl: ""
url: "https://jerome-celle.github.io/"

scripts:
  - jquery.min.js
  - skel.min.js
  - util.js
  - main.js

stylesheets:
  - main.css
  - custom.css

menus:
    - text: Accueil
      url: /
    - text: Projets
      url: /projects/
    - text: contact
      url: /contact/

collections:
  project:
    output: true
    permalink: /project/:path/

socialMedias:
  - slug: twitter
    username: jeffy38130
    url: https://twitter.com/jeffy38130
    label: Twitter
    icon: fa-twitter
  - slug: github
    username: jerome-celle
    url: https://github.com/Jerome-Celle
    label: Twitter
    icon: fa-github
  - slug: linkedin
    username: ""
    url: https://www.linkedin.com/in/j%C3%A9r%C3%B4me-celle-9683b0b9?trk=hp-identity-name
    label: Linkedin
    icon: fa-linkedin

about: Grand amoureux des sciences, j'ai une affection toute particulière pour les nouvelles technologies en rapport avec l'informatique!

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
